from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


@dataclass(frozen=True)
class TaskPayloadHooks:
    normalize_task_id: Callable[[str], str]
    normalize_timestamp_fields: Callable[[dict[str, Any]], dict[str, Any]]


def normalize_task_spec_payload(
    raw: dict[str, Any],
    *,
    version: int,
    default_cpu_retry_max_attempts: int,
    default_startup_failure_seconds: int,
    hooks: TaskPayloadHooks,
) -> dict[str, Any]:
    task_id = str(raw.get("task_id", "")).strip()
    task_key = hooks.normalize_task_id(str(raw.get("task_key", task_id)).strip() or task_id)
    payload = dict(raw)
    payload.setdefault("version", version)
    payload.setdefault("execution_mode", "shell")
    payload["task_key"] = task_key
    payload.setdefault("client_task_id", "")
    payload.setdefault("client_task_key", "")
    payload.setdefault("feedback_mode", "auto")
    payload.setdefault("command_template", str(payload.get("command", "")))
    payload.setdefault("owner_tenant", "")
    payload.setdefault("owner_role", "")
    payload.setdefault("owner_label", "")
    payload.setdefault("submitted_via_api", False)
    payload.setdefault("require_signal_to_unblock", payload.get("execution_mode") == "codex_subagent")
    payload.setdefault("depends_on", [])
    payload.setdefault("required_artifact_globs", [])
    payload.setdefault("required_report_conditions", [])
    payload.setdefault("report_format", "auto")
    payload.setdefault("report_keys", [])
    payload.setdefault("report_contract", "")
    payload.setdefault("agent_name", "")
    payload.setdefault("codex_session_id", "")
    payload.setdefault("proposal_path", "")
    payload.setdefault("proposal_source", "")
    payload.setdefault("proposal_owner", False)
    payload.setdefault("closeout_proposal_dir", "")
    payload.setdefault("closeout_proposal_dir_source", "")
    payload.setdefault("project_history_file", "")
    payload.setdefault("project_history_file_source", "")
    payload.setdefault("allow_session_rebind", False)
    payload.setdefault("priority", 0)
    payload.setdefault("gpu_slots", 0)
    payload.setdefault("cpu_profile", "auto")
    payload.setdefault("cpu_threads", 0)
    payload.setdefault("cpu_threads_min", 0)
    payload.setdefault("cpu_threads_max", 0)
    payload.setdefault("cpu_threads_mode", "")
    payload.setdefault("cpu_thread_source", "")
    payload.setdefault("assigned_cpu_threads", 0)
    payload.setdefault("cpu_workers", 0)
    payload.setdefault("cpu_workers_min", 0)
    payload.setdefault("cpu_workers_max", 0)
    payload.setdefault("cpu_worker_source", "")
    payload.setdefault("assigned_cpu_workers", 0)
    payload.setdefault("cpu_retry_attempts", 0)
    payload.setdefault("cpu_retry_max_attempts", default_cpu_retry_max_attempts)
    payload.setdefault("cpu_retry_last_reason", "")
    payload.setdefault("gpu_min_free_mb", 0)
    payload.setdefault("gpu_max_util_percent", 0)
    payload.setdefault("assigned_gpus", [])
    payload.setdefault("allowed_gpus", [])
    payload.setdefault("replace_existing", True)
    payload.setdefault("success_prompt", "")
    payload.setdefault("failure_prompt", "")
    payload.setdefault("task_note", "")
    payload.setdefault("artifact_globs", [])
    payload.setdefault("env", {})
    payload.setdefault("executor_name", "")
    payload.setdefault("executor_type", "")
    payload.setdefault("executor_target", "")
    payload.setdefault("executor_identity_file", "")
    payload.setdefault("executor_ssh_options", [])
    payload.setdefault("executor_host_gpu_ids", [])
    payload.setdefault("executor_remote_gpu_ids", [])
    payload.setdefault("executor_remote_workdir_prefix", "")
    payload.setdefault("executor_remote_home", "")
    payload.setdefault("executor_remote_codex_home", "")
    payload.setdefault("executor_remote_codex_bin", "codex")
    payload.setdefault("executor_default_env", {})
    payload.setdefault("remote_workdir", "")
    payload.setdefault("codex_exec_mode", "dangerous")
    payload.setdefault("resume_timeout_seconds", 7200)
    payload.setdefault("launch_grace_seconds", 0)
    payload.setdefault("prompt_max_chars", 12000)
    payload.setdefault("log_tail_lines", 80)
    payload.setdefault("log_tail_chars", 5000)
    payload.setdefault("artifact_max_chars", 1200)
    payload.setdefault("artifact_max_lines", 40)
    payload.setdefault("startup_failure_threshold_seconds", default_startup_failure_seconds)
    payload.setdefault("fallback_provider", "")
    payload.setdefault("subagent_model", "gpt-5.4")
    payload.setdefault("subagent_exec_mode", "dangerous")
    payload.setdefault("subagent_timeout_seconds", 7200)
    payload.setdefault("subagent_continue_attempts", 3)
    payload.setdefault("subagent_prompt", "")
    return hooks.normalize_timestamp_fields(payload)


def normalize_task_state_payload(
    raw: dict[str, Any],
    *,
    version: int,
    default_cpu_retry_max_attempts: int,
    hooks: TaskPayloadHooks,
) -> dict[str, Any]:
    task_id = str(raw.get("task_id", "")).strip()
    task_key = hooks.normalize_task_id(str(raw.get("task_key", task_id)).strip() or task_id)
    payload = dict(raw)
    payload.setdefault("version", version)
    payload["task_key"] = task_key
    payload.setdefault("client_task_id", "")
    payload.setdefault("client_task_key", "")
    payload.setdefault("execution_mode", "shell")
    payload.setdefault("agent_name", "")
    payload.setdefault("codex_session_id", "")
    payload.setdefault("proposal_path", "")
    payload.setdefault("proposal_source", "")
    payload.setdefault("proposal_owner", False)
    payload.setdefault("closeout_proposal_dir", "")
    payload.setdefault("closeout_proposal_dir_source", "")
    payload.setdefault("project_history_file", "")
    payload.setdefault("project_history_file_source", "")
    payload.setdefault("allow_session_rebind", False)
    payload.setdefault("priority", 0)
    payload.setdefault("gpu_slots", 0)
    payload.setdefault("cpu_profile", "auto")
    payload.setdefault("cpu_threads", 0)
    payload.setdefault("cpu_threads_min", 0)
    payload.setdefault("cpu_threads_max", 0)
    payload.setdefault("cpu_threads_mode", "")
    payload.setdefault("cpu_thread_source", "")
    payload.setdefault("assigned_cpu_threads", 0)
    payload.setdefault("cpu_workers", 0)
    payload.setdefault("cpu_workers_min", 0)
    payload.setdefault("cpu_workers_max", 0)
    payload.setdefault("cpu_worker_source", "")
    payload.setdefault("assigned_cpu_workers", 0)
    payload.setdefault("cpu_retry_attempts", 0)
    payload.setdefault("cpu_retry_max_attempts", default_cpu_retry_max_attempts)
    payload.setdefault("cpu_retry_last_reason", "")
    payload.setdefault("assigned_gpus", [])
    payload.setdefault("allowed_gpus", [])
    payload.setdefault("feedback_mode", "auto")
    payload.setdefault("pending_feedback", False)
    payload.setdefault("owner_tenant", "")
    payload.setdefault("owner_role", "")
    payload.setdefault("owner_label", "")
    payload.setdefault("submitted_via_api", False)
    payload.setdefault("require_signal_to_unblock", payload.get("execution_mode") == "codex_subagent")
    payload.setdefault("taskboard_signal", "")
    payload.setdefault("needs_attention", False)
    payload.setdefault("attention_reason", "")
    payload.setdefault("attention_message", "")
    payload.setdefault("depends_on", [])
    payload.setdefault("executor_name", "")
    payload.setdefault("remote_workdir", "")
    payload.setdefault("why_started", "")
    payload.setdefault("dispatch_gpu_snapshot", [])
    payload.setdefault("launch_gpu_snapshot", [])
    payload.setdefault("rejected_reason", "")
    payload.setdefault("followup_status", "")
    payload.setdefault("followup_last_signal", "")
    payload.setdefault("followup_last_action", "")
    payload.setdefault("followup_stopped_at", "")
    payload.setdefault("followup_last_message_path", "")
    payload.setdefault("notification_signal", "")
    return hooks.normalize_timestamp_fields(payload)
